"use client";

import type { Dispatch, SetStateAction } from "react";

type Tenant = { firstName: string; initial: string; lastName: string; email: string; phone: string; dateOfBirth: string; isMinor: boolean };
type SectionState = Record<string, string | boolean | string[] | undefined>;
type Landlord = { firstName: string; initial: string; lastName: string; name: string; email: string; password: string; phoneHome: string; phoneBusiness: string; civicAddress: string; mailingAddress: string };

type Props = {
  page: string;
  landlord: Landlord;
  setLandlord: Dispatch<SetStateAction<Landlord>>;
  tenants: Tenant[];
  updateTenant: (index: number, field: keyof Tenant, value: string) => void;
  addTenant: () => void;
  removeTenant: (index: number) => void;
  formData: Record<string, SectionState>;
  updateFormValue: (section: string, key: string, value: string | boolean | string[] | undefined) => void;
};

export default function FormPSectionPage({ page, landlord, setLandlord, tenants, updateTenant, addTenant, removeTenant, formData, updateFormValue }: Props) {
  const field = (label: string, value: string, onChange: (value: string) => void, type = "text") => <label>{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} /></label>;
  const area = (label: string, value: string, onChange: (value: string) => void) => <label className="full-width">{label}<textarea value={value} onChange={(event) => onChange(event.target.value)} /></label>;
  const sectionKey = (id: string) => (id.startsWith("section") ? id : `section${id}`);
  const section = (id: string) => formData[sectionKey(id)] ?? {};
  const value = (id: string, key: string) => String(section(id)[key] ?? "");
  const setValue = (id: string, key: string, next: string | boolean) => updateFormValue(sectionKey(id), key, next);
  const check = (id: string, key: string, label: string) => <label className="checkbox-row"><input type="checkbox" checked={Boolean(section(id)[key])} onChange={(event) => setValue(id, key, event.target.checked)} />{label}</label>;

  if (page === "landlord") return <div className="field-grid">
    {field("First name", landlord.firstName, (next) => setLandlord((current) => ({ ...current, firstName: next, name: [next, current.initial, current.lastName].filter(Boolean).join(" ") })))}
    {field("Initial", landlord.initial, (next) => setLandlord((current) => ({ ...current, initial: next, name: [current.firstName, next, current.lastName].filter(Boolean).join(" ") })))}
    {field("Last name", landlord.lastName, (next) => setLandlord((current) => ({ ...current, lastName: next, name: [current.firstName, current.initial, next].filter(Boolean).join(" ") })))}
    {field("Home phone", landlord.phoneHome, (next) => setLandlord((current) => ({ ...current, phoneHome: next })))}
    {field("Business / other phone", landlord.phoneBusiness, (next) => setLandlord((current) => ({ ...current, phoneBusiness: next })))}
    {field("Email", landlord.email, (next) => setLandlord((current) => ({ ...current, email: next })), "email")}
    {field("Password", landlord.password, (next) => setLandlord((current) => ({ ...current, password: next })), "password")}
    {area("Civic address", landlord.civicAddress, (next) => setLandlord((current) => ({ ...current, civicAddress: next })))}
    {area("Mailing address", landlord.mailingAddress, (next) => setLandlord((current) => ({ ...current, mailingAddress: next })))}
  </div>;

  if (page === "tenants") return <div className="tenant-section"><div className="tenant-intro"><div><h3>Tenants and occupants</h3><p>Adults 18 or older are tenants and must sign. Anyone under 18 is an occupant without signing rights.</p></div></div>{tenants.map((tenant, index) => <div className="tenant-card" key={`${tenant.email}-${index}`}><div className="tenant-card-head"><strong>{tenant.firstName || `Tenant ${index + 1}`}</strong><span className={`role-tag ${tenant.isMinor ? "occupant" : "tenant"}`}>{tenant.isMinor ? "Occupant" : "Tenant"}</span></div><div className="field-grid">{field("First name", tenant.firstName, (next) => updateTenant(index, "firstName", next))}{field("Initial", tenant.initial, (next) => updateTenant(index, "initial", next))}{field("Last name", tenant.lastName, (next) => updateTenant(index, "lastName", next))}{field("Email", tenant.email, (next) => updateTenant(index, "email", next), "email")}{field("Phone", tenant.phone, (next) => updateTenant(index, "phone", next))}{field("Date of birth", tenant.dateOfBirth, (next) => updateTenant(index, "dateOfBirth", next), "date")}</div>{tenants.length > 1 && <button type="button" className="remove-button" onClick={() => removeTenant(index)}>Remove</button>}</div>)}<button type="button" className="add-button" onClick={addTenant}>+ Add another tenant or occupant</button></div>;

  if (page === "occupants") return <div className="field-grid">{area("Other adults or children occupying the premises", value("2", "otherOccupants"), (next) => setValue("2", "otherOccupants", next))}{area("Occupancy rule", "Only those tenants and occupants named are allowed to live in the premises without written consent of the landlord.", () => undefined)}</div>;
  if (page === "premises") return <div className="field-grid">{area("Rental civic address", value("3", "premisesAddress"), (next) => setValue("3", "premisesAddress", next))}{field("Apartment / suite", value("3", "unitNumber"), (next) => setValue("3", "unitNumber", next))}<label>Property type<select value={value("3", "propertyType")} onChange={(event) => setValue("3", "propertyType", event.target.value)}><option value="">Select</option><option>Detached</option><option>Semi-detached</option><option>Apartment</option><option>Duplex</option><option>Condominium</option><option>Mobile home</option></select></label>{area("Tenant mailing address", value("3", "tenantMailingAddress"), (next) => setValue("3", "tenantMailingAddress", next))}{field("Tenant contact numbers", value("3", "tenantContactNumbers"), (next) => setValue("3", "tenantContactNumbers", next))}</div>;
  if (page === "emergency") return <div className="field-grid">{field("Next of kin / emergency contact", value("4", "nextOfKinName"), (next) => setValue("4", "nextOfKinName", next))}{field("Emergency contact phone", value("4", "nextOfKinPhone"), (next) => setValue("4", "nextOfKinPhone", next))}</div>;
  if (page === "contacts") return <div className="field-grid">{field("Property manager / agent", value("5", "agentName"), (next) => setValue("5", "agentName", next))}{field("Agent phone", value("5", "agentPhone"), (next) => setValue("5", "agentPhone", next))}{area("Agent address", value("5", "agentAddress"), (next) => setValue("5", "agentAddress", next))}{field("Building superintendent", value("6", "superintendentName"), (next) => setValue("6", "superintendentName", next))}{field("Superintendent phone", value("6", "superintendentPhone"), (next) => setValue("6", "superintendentPhone", next))}{area("Superintendent address", value("6", "superintendentAddress"), (next) => setValue("6", "superintendentAddress", next))}</div>;
  if (page === "service") return <div className="field-grid">{field("Landlord electronic service address (7A)", value("7A", "landlordServiceEmail"), (next) => setValue("7A", "landlordServiceEmail", next), "email")}{area("Service rule", "Electronic service is optional and must comply with Section 15 of the Residential Tenancies Act.", () => undefined)}</div>;
  if (page === "lease") return <div className="field-grid"><label>Lease type<select value={value("8", "leaseType")} onChange={(event) => setValue("8", "leaseType", event.target.value)}><option value="">Select</option><option value="Periodic">8A · Periodic lease</option><option value="Fixed-term">8B · Fixed-term lease</option></select></label>{value("8", "leaseType") === "Periodic" && <label>Frequency<select value={value("8A", "frequency")} onChange={(event) => setValue("8A", "frequency", event.target.value)}><option value="">Select</option><option>Year-to-year</option><option>Month-to-month</option><option>Week-to-week</option></select></label>}{field("Start date", value("8", "startDate"), (next) => setValue("8", "startDate", next), "date")}{value("8", "leaseType") === "Fixed-term" && field("End date", value("8B", "endDate"), (next) => setValue("8B", "endDate", next), "date")}{area("Fixed-term termination warning", "A fixed-term lease ends on the date stated in this agreement and does not automatically renew unless the parties agree in writing.", () => undefined)}</div>;
  if (page === "housing") return <div className="field-grid">{check("9", "publicHousing", "This is a public housing lease")}{area("Public housing rule", "The tenant must remain eligible under the applicable public housing program and required program documents must be attached.", () => undefined)}</div>;
  if (page === "rentIncrease") return <div className="field-grid">{area("Statutory rent-increase conditions", "Rent cannot be increased until at least 12 months after the last increase. The landlord must give four months' notice for month-to-month or year-to-year leases and eight weeks' notice for week-to-week leases.", () => undefined)}{field("Last rent increase date", value("11", "lastIncreaseDate"), (next) => setValue("11", "lastIncreaseDate", next), "date")}{field("Notice period", value("11", "noticePeriod"), (next) => setValue("11", "noticePeriod", next))}</div>;
  if (page === "rent") return <div className="field-grid">{field("Rent amount", value("10", "amount"), (next) => setValue("10", "amount", next), "number")}<label>Rent frequency<select value={value("10", "frequency")} onChange={(event) => setValue("10", "frequency", event.target.value)}><option value="">Select</option><option>Weekly</option><option>Monthly</option></select></label><label>Payment method<select value={value("10", "paymentMethod")} onChange={(event) => setValue("10", "paymentMethod", event.target.value)}><option value="">Select</option><option>Cash</option><option>E-transfer</option><option>Pre-authorized debit</option><option>Post-dated cheques</option><option>Other</option></select></label>{field("Payable to", value("10", "payableTo"), (next) => setValue("10", "payableTo", next))}{area("Late fee clause", "A late fee must not exceed 1% per month of overdue rent and may only be charged as permitted by law.", () => undefined)}</div>;
  if (page === "services") return <div className="field-grid">{check("13", "stove", "Stove included")}{check("13", "refrigerator", "Refrigerator included")}{check("13", "washerDryer", "Washer / dryer included")}{check("13", "dishwasher", "Dishwasher included")}{check("13", "heat", "Heat included")}{check("13", "water", "Water included")}{check("13", "electricity", "Electricity included")}{check("13", "parking", "Parking included")}{check("13", "wifi", "Wi-Fi included")}{area("Tenant responsibilities", value("13", "tenantResponsibilities"), (next) => setValue("13", "tenantResponsibilities", next))}</div>;
  if (page === "inspection") return <div className="field-grid">{labelText("Inspection report status", value("16", "inspectionReport"), (next) => setValue("16", "inspectionReport", next))}{check("16", "tenantReceivedReport", "Tenant received a copy of the inspection report")}</div>;
  if (page === "conditions") return <div className="field-grid">{area("Statutory conditions", value("17", "statutoryConditions"), (next) => setValue("17", "statutoryConditions", next))}{check("17", "buildingRulesAttached", "Building rules attached and provided")}</div>;
  if (page === "arrears") return <div className="field-grid">{area("Rental arrears policy", "For rental arrears, the landlord must provide the statutory notice and opportunity to pay, including the applicable 15-day period.", () => undefined)}{area("Additional arrears terms", value("18", "arrearsRules"), (next) => setValue("18", "arrearsRules", next))}</div>;
  if (page === "notice") return <div className="field-grid">{area("Tenant notice to quit rules", value("19", "noticeToQuit"), (next) => setValue("19", "noticeToQuit", next))}</div>;
  if (page === "attachments") return <div className="field-grid">{check("26", "actCopy", "Residential Tenancies Act copy or access provided")}{check("26", "signedLeaseCopy", "Signed lease copy will be provided")}{check("26", "buildingRulesCopy", "Building rules provided")}{area("Additional acknowledgments", value("26", "acknowledgments"), (next) => setValue("26", "acknowledgments", next))}</div>;
  return <div className="summary-layout"><div className="summary-card"><h3>Landlord and tenants</h3><p>{landlord.name || "Landlord not entered"}</p>{tenants.map((tenant, index) => <p key={index}>{tenant.firstName} {tenant.lastName} · {tenant.isMinor ? "Occupant" : "Tenant"}</p>)}</div><div className="summary-card"><h3>Premises and rent</h3><p>{value("3", "premisesAddress") || "Premises not entered"}</p><p>{value("10", "amount") || "Rent not entered"}</p><p>{value("8", "leaseType") || "Lease type not selected"}</p></div></div>;
}

function labelText(label: string, value: string, onChange: (value: string) => void) {
  return <label>{label}<input value={value} onChange={(event) => onChange(event.target.value)} /></label>;
}
