"use client";

import { FormEvent, useState } from "react";
import SignaturePad from "@/components/signature-pad";

type TenantSigningFormProps = {
  token: string;
  leaseCreatedAt: string;
  tenant: { firstName: string; lastName: string; email: string; signedAt: string | null; signatureData: string | null };
};

export default function TenantSigningForm({ token, leaseCreatedAt, tenant }: TenantSigningFormProps) {
  const [form, setForm] = useState({ emergencyContactName: "", emergencyContactPhone: "", serviceEmail: tenant.email, acknowledgeTruth: false, acknowledgeElectronicDelivery: false, acknowledgeAgreement: false, signatureData: tenant.signatureData ?? "" });
  const [status, setStatus] = useState(tenant.signedAt ? "signed" : "editing");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);

  function update(field: keyof typeof form, value: string | boolean) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(`/api/tenant/sign/${token}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setStatus("signed"); } catch (submissionError) { setError(submissionError instanceof Error ? submissionError.message : "Unable to save your signature."); } finally { setSaving(false); } }

  if (status === "signed") return <main className="signing-page"><section className="signing-card confirmation-card"><span className="eyebrow">Signature received</span><h1>Thank you, {tenant.firstName}.</h1><p>Your signed information has been securely saved. The landlord will receive the completed agreement when all adult tenants have signed.</p><div className="confirmation-meta"><span>Tenant</span><strong>{tenant.firstName} {tenant.lastName}</strong><span>Submitted</span><strong>{tenant.signedAt ? new Date(tenant.signedAt).toLocaleDateString() : "Just now"}</strong></div></section></main>;

  return <main className="signing-page"><section className="signing-card"><header className="signing-header"><span className="eyebrow">Private tenant signing</span><h1>Review and sign your lease.</h1><p>Hi {tenant.firstName}. Complete the final details below, then draw your signature. This link is unique to you.</p><span className="lease-date">Lease started {new Date(leaseCreatedAt).toLocaleDateString()}</span></header><form onSubmit={submit} className="signing-form"><section className="signing-section"><span className="section-number">01</span><div><h2>Emergency contact</h2><p>Someone we can contact if there is an urgent issue.</p><div className="field-grid"><label>Full name<input value={form.emergencyContactName} onChange={(event) => update("emergencyContactName", event.target.value)} placeholder="Jordan Lee" /></label><label>Phone number<input value={form.emergencyContactPhone} onChange={(event) => update("emergencyContactPhone", event.target.value)} placeholder="(555) 014-2026" /></label></div></div></section><section className="signing-section"><span className="section-number">02</span><div><h2>Electronic service</h2><p>Choose the email address where statutory notices can be delivered.</p><label>Email for electronic service<input type="email" value={form.serviceEmail} onChange={(event) => update("serviceEmail", event.target.value)} /></label></div></section><section className="signing-section"><span className="section-number">03</span><div><h2>Statutory acknowledgments</h2><p>Please confirm each statement before signing.</p><label className="check-row"><input type="checkbox" checked={form.acknowledgeTruth} onChange={(event) => update("acknowledgeTruth", event.target.checked)} /> I confirm that the information I provided is true and complete.</label><label className="check-row"><input type="checkbox" checked={form.acknowledgeElectronicDelivery} onChange={(event) => update("acknowledgeElectronicDelivery", event.target.checked)} /> I consent to receive statutory notices electronically at the email above.</label><label className="check-row"><input type="checkbox" checked={form.acknowledgeAgreement} onChange={(event) => update("acknowledgeAgreement", event.target.checked)} /> I have reviewed the lease terms and agree to sign this agreement electronically.</label></div></section><section className="signing-section signature-section"><span className="section-number">04</span><div><h2>Your signature</h2><p>Draw your signature in the box, then save it before submitting.</p><SignaturePad initialSignature={tenant.signatureData} onSave={(signatureData) => update("signatureData", signatureData)} />{error && <p className="error-message">{error}</p>}<button type="submit" className="primary-button submit-signature" disabled={saving || !form.signatureData}>{saving ? "Submitting..." : "Submit signed lease"} <span>→</span></button></div></section></form></section></main>;
}